name: Check Code

on:
  pull_request:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Dependancy
        run: npm ci

      - name: Lint
        run: npm run lint:diff
        env:
          CI: true
          BASE: ${{ github.base_ref }}
          HEAD: ${{ github.head_ref }}

      - name: Test
        run: npm run test:cov
